// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUsPellYN_x7vCgJOkEDU30A7ncmIswq4',
    appId: '1:634835680675:web:f0a32b41e189305a1dae16',
    messagingSenderId: '634835680675',
    projectId: 'speat-701ea',
    authDomain: 'speat-701ea.firebaseapp.com',
    storageBucket: 'speat-701ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjDqOhXWd6syZebMqBortrDvhkSeTksFc',
    appId: '1:634835680675:android:cd97d16fde41d5341dae16',
    messagingSenderId: '634835680675',
    projectId: 'speat-701ea',
    storageBucket: 'speat-701ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtx27FTMpNrHWEabCQaudlOehAvc4yDnw',
    appId: '1:634835680675:ios:1fe55fc37cd29e061dae16',
    messagingSenderId: '634835680675',
    projectId: 'speat-701ea',
    storageBucket: 'speat-701ea.appspot.com',
    iosBundleId: 'com.speat.appSpeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtx27FTMpNrHWEabCQaudlOehAvc4yDnw',
    appId: '1:634835680675:ios:51274859492727021dae16',
    messagingSenderId: '634835680675',
    projectId: 'speat-701ea',
    storageBucket: 'speat-701ea.appspot.com',
    iosBundleId: 'com.speat.appSpeat.RunnerTests',
  );
}
